[package]
name = "wgpu_update"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.1.4", features = ["derive"] }
serde = "1.0.152"
serde_derive = "1.0.152"
toml = "0.6.0"

